"""Allow same measure with different time_of_day in care plans and schedules

Revision ID: 254964d334b9
Revises: 7c384d9f8b38
Create Date: 2026-03-24 09:20:49.906635

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "254964d334b9"
down_revision: Union[str, Sequence[str], None] = "7c384d9f8b38"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("uq__customer_measure"), "customer_measures", type_="unique")
    op.create_unique_constraint(
        "uq__customer_measure_time",
        "customer_measures",
        ["customer_id", "measure_id", "time_of_day"],
    )
    op.drop_constraint(
        op.f("uq__schedule_customer_measure"), "schedule_measure", type_="unique"
    )
    op.create_unique_constraint(
        "uq__schedule_customer_measure_time",
        "schedule_measure",
        ["schedule_id", "customer_id", "measure_id", "time_of_day"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq__schedule_customer_measure_time", "schedule_measure", type_="unique"
    )
    op.create_unique_constraint(
        op.f("uq__schedule_customer_measure"),
        "schedule_measure",
        ["schedule_id", "customer_id", "measure_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.drop_constraint("uq__customer_measure_time", "customer_measures", type_="unique")
    op.create_unique_constraint(
        op.f("uq__customer_measure"),
        "customer_measures",
        ["customer_id", "measure_id"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
