"""Redesign schedule and care visit models

Revision ID: 408359792a8f
Revises: d0c195e9238d
Create Date: 2026-03-22 00:35:30.586368

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "408359792a8f"
down_revision: Union[str, Sequence[str], None] = "d0c195e9238d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("measure_care_visit")
    op.add_column(
        "schedule_measure", sa.Column("customer_id", sa.UUID(), nullable=False)
    )
    op.create_unique_constraint(
        "uq__schedule_customer_measure",
        "schedule_measure",
        ["schedule_id", "customer_id", "measure_id"],
    )
    op.create_foreign_key(None, "schedule_measure", "customers", ["customer_id"], ["id"])
    op.add_column(
        "schedules",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.create_check_constraint(
        "ck__schedule_has_shift",
        "schedules",
        "shift_type IS NOT NULL OR custom_shift IS NOT NULL",
    )
    op.create_index(
        "uq__schedule_date_shift",
        "schedules",
        ["date", "shift_type"],
        unique=True,
        postgresql_where=sa.text("shift_type IS NOT NULL"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "uq__schedule_date_shift",
        table_name="schedules",
        postgresql_where=sa.text("shift_type IS NOT NULL"),
    )
    op.drop_constraint("ck__schedule_has_shift", "schedules", type_="check")
    op.drop_column("schedules", "updated_at")
    op.drop_constraint(
        "schedule_measure_customer_id_fkey", "schedule_measure", type_="foreignkey"
    )
    op.drop_constraint(
        "uq__schedule_customer_measure", "schedule_measure", type_="unique"
    )
    op.drop_column("schedule_measure", "customer_id")
    op.create_table(
        "measure_care_visit",
        sa.Column("measure_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("care_visit_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["care_visit_id"],
            ["care_visits.id"],
            name=op.f("measure_care_visit_care_visit_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["measure_id"],
            ["measures.id"],
            name=op.f("measure_care_visit_measure_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "measure_id", "care_visit_id", name=op.f("measure_care_visit_pkey")
        ),
    )
    # ### end Alembic commands ###
