"""Add permissions and audit_entries tables

Revision ID: 7c384d9f8b38
Revises: 408359792a8f
Create Date: 2026-03-22 19:29:53.681072

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7c384d9f8b38"
down_revision: Union[str, Sequence[str], None] = "408359792a8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_entries",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("resource_type", sa.String(length=50), nullable=False),
        sa.Column("resource_id", sa.UUID(), nullable=False),
        sa.Column("changes", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_audit_created_at", "audit_entries", ["created_at"], unique=False)
    op.create_index(
        "ix_audit_resource",
        "audit_entries",
        ["resource_type", "resource_id"],
        unique=False,
    )
    op.create_index("ix_audit_user", "audit_entries", ["user_id"], unique=False)
    op.create_table(
        "permissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("principal", sa.String(), nullable=False),
        sa.Column("resource", sa.String(), nullable=False),
        sa.Column("action", sa.String(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("principal", "resource", name="uq__permission"),
    )
    op.create_index(
        "ix_permission_principal", "permissions", ["principal"], unique=False
    )
    op.create_index("ix_permission_resource", "permissions", ["resource"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_permission_resource", table_name="permissions")
    op.drop_index("ix_permission_principal", table_name="permissions")
    op.drop_table("permissions")
    op.drop_index("ix_audit_user", table_name="audit_entries")
    op.drop_index("ix_audit_resource", table_name="audit_entries")
    op.drop_index("ix_audit_created_at", table_name="audit_entries")
    op.drop_table("audit_entries")
    # ### end Alembic commands ###
