"""Add planned_start_time to CareVisit and care_visit_id to ScheduleMeasure

Revision ID: a29830265be3
Revises: 254964d334b9
Create Date: 2026-03-24 21:33:24.297197

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a29830265be3"
down_revision: Union[str, Sequence[str], None] = "254964d334b9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "care_visits", sa.Column("planned_start_time", sa.Time(), nullable=True)
    )
    op.create_index(
        "ix_care_visit_schedule_start",
        "care_visits",
        ["schedule_id", "planned_start_time"],
        unique=False,
    )
    op.add_column(
        "schedule_measure", sa.Column("care_visit_id", sa.UUID(), nullable=True)
    )
    op.create_foreign_key(
        "fk_schedule_measure_care_visit_id",
        "schedule_measure",
        "care_visits",
        ["care_visit_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "fk_schedule_measure_care_visit_id", "schedule_measure", type_="foreignkey"
    )
    op.drop_column("schedule_measure", "care_visit_id")
    op.drop_index("ix_care_visit_schedule_start", table_name="care_visits")
    op.drop_column("care_visits", "planned_start_time")
    # ### end Alembic commands ###
