"""Initial schema

Revision ID: d0c195e9238d
Revises:
Create Date: 2026-03-21 20:18:59.236401

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d0c195e9238d"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "customers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("key_number", sa.Integer(), nullable=False),
        sa.Column("address", sa.String(length=255), nullable=False),
        sa.Column("care_level", sa.String(), nullable=True),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("approved_hours", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("key_number"),
    )
    op.create_table(
        "measures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("default_duration", sa.Integer(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("time_of_day", sa.String(length=20), nullable=True),
        sa.Column("time_flexibility", sa.String(length=20), nullable=True),
        sa.Column("is_standard", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        "ix_measure_active_time", "measures", ["is_active", "time_of_day"], unique=False
    )
    op.create_index("ix_measure_is_active", "measures", ["is_active"], unique=False)
    op.create_index("ix_measure_time_of_day", "measures", ["time_of_day"], unique=False)
    op.create_table(
        "schedule_archives",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("original_schedule_id", sa.UUID(), nullable=False),
        sa.Column("original_date", sa.Date(), nullable=False),
        sa.Column("shift_type", sa.String(), nullable=True),
        sa.Column("custom_shift", sa.String(length=50), nullable=True),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "archived_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedules",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("shift_type", sa.String(), nullable=True),
        sa.Column("custom_shift", sa.String(length=50), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_schedule_date", "schedules", ["date"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("hashed_password", sa.String(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "care_visits",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("duration", sa.Integer(), nullable=False),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_care_visit_customer_date",
        "care_visits",
        ["customer_id", "date"],
        unique=False,
    )
    op.create_index("ix_care_visit_date", "care_visits", ["date"], unique=False)
    op.create_index(
        "ix_care_visit_schedule_date",
        "care_visits",
        ["schedule_id", "date"],
        unique=False,
    )
    op.create_index("ix_care_visit_status", "care_visits", ["status"], unique=False)
    op.create_index(
        "ix_care_visit_status_date", "care_visits", ["status", "date"], unique=False
    )
    op.create_table(
        "customer_measures",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.Column("measure_id", sa.UUID(), nullable=False),
        sa.Column("frequency", sa.String(), nullable=False),
        sa.Column(
            "days_of_week", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("occurrences_per_week", sa.Integer(), nullable=True),
        sa.Column("customer_duration", sa.Integer(), nullable=True),
        sa.Column("customer_notes", sa.Text(), nullable=True),
        sa.Column("time_of_day", sa.String(length=20), nullable=True),
        sa.Column("time_flexibility", sa.String(length=20), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["measure_id"],
            ["measures.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("customer_id", "measure_id", name="uq__customer_measure"),
    )
    op.create_table(
        "employees",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("phone", sa.String(length=20), nullable=True),
        sa.Column("gender", sa.String(length=10), nullable=True),
        sa.Column("birth_date", sa.Date(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("role", sa.String(), nullable=True),
        sa.Column("employment_type", sa.String(), nullable=True),
        sa.Column("employment_degree", sa.Integer(), nullable=True),
        sa.Column("weekly_hours", sa.Float(), nullable=True),
        sa.Column("vacation_days", sa.Integer(), nullable=True),
        sa.Column("is_summer_worker", sa.Boolean(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "schedule_customer",
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("customer_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["customer_id"],
            ["customers.id"],
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
        ),
        sa.PrimaryKeyConstraint("schedule_id", "customer_id"),
    )
    op.create_table(
        "schedule_measure",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("measure_id", sa.UUID(), nullable=False),
        sa.Column("time_of_day", sa.String(length=20), nullable=True),
        sa.Column("custom_duration", sa.Integer(), nullable=True),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["measure_id"],
            ["measures.id"],
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "absences",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("absence_type", sa.String(), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("hours", sa.Float(), nullable=True),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_absence_employee_dates",
        "absences",
        ["employee_id", "start_date", "end_date"],
        unique=False,
    )
    op.create_index("ix_absence_employee_id", "absences", ["employee_id"], unique=False)
    op.create_table(
        "employee_care_visit",
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.Column("care_visit_id", sa.UUID(), nullable=False),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column("notes", sa.String(length=255), nullable=True),
        sa.ForeignKeyConstraint(
            ["care_visit_id"],
            ["care_visits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.PrimaryKeyConstraint("employee_id", "care_visit_id"),
    )
    op.create_table(
        "measure_care_visit",
        sa.Column("measure_id", sa.UUID(), nullable=False),
        sa.Column("care_visit_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["care_visit_id"],
            ["care_visits.id"],
        ),
        sa.ForeignKeyConstraint(
            ["measure_id"],
            ["measures.id"],
        ),
        sa.PrimaryKeyConstraint("measure_id", "care_visit_id"),
    )
    op.create_table(
        "schedule_employee",
        sa.Column("schedule_id", sa.UUID(), nullable=False),
        sa.Column("employee_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["employees.id"],
        ),
        sa.ForeignKeyConstraint(
            ["schedule_id"],
            ["schedules.id"],
        ),
        sa.PrimaryKeyConstraint("schedule_id", "employee_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("schedule_employee")
    op.drop_table("measure_care_visit")
    op.drop_table("employee_care_visit")
    op.drop_index("ix_absence_employee_id", table_name="absences")
    op.drop_index("ix_absence_employee_dates", table_name="absences")
    op.drop_table("absences")
    op.drop_table("schedule_measure")
    op.drop_table("schedule_customer")
    op.drop_table("employees")
    op.drop_table("customer_measures")
    op.drop_index("ix_care_visit_status_date", table_name="care_visits")
    op.drop_index("ix_care_visit_status", table_name="care_visits")
    op.drop_index("ix_care_visit_schedule_date", table_name="care_visits")
    op.drop_index("ix_care_visit_date", table_name="care_visits")
    op.drop_index("ix_care_visit_customer_date", table_name="care_visits")
    op.drop_table("care_visits")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_schedule_date", table_name="schedules")
    op.drop_table("schedules")
    op.drop_table("schedule_archives")
    op.drop_index("ix_measure_time_of_day", table_name="measures")
    op.drop_index("ix_measure_is_active", table_name="measures")
    op.drop_index("ix_measure_active_time", table_name="measures")
    op.drop_table("measures")
    op.drop_table("customers")
    # ### end Alembic commands ###
